{
	"Alliance": "Alliance",
	"Click here to change the active realm": "Click here to change the active realm",
	"Price per item - Last 48 hours": "Price per item - Last 48 hours",
	"Average price per item - Last month": "Average price per item - Last month",
	"Bid": "Bid",
	"Buyout": "Buyout",
	"Horde": "Horde",
	"Neutral": "Neutral",
	"Options": "Options",
	"Watch": "Watch",
	"Qty": "Qty",
	"Bids": "Bids",
	"Seller": "Seller",
	"Time Left": "Time Left",
	"Check %s at Wowhead": "Check %s at Wowhead",
	"Please note that comments are shared across all realms but are locale specific (comments made on the french AHSpy site will not show up on the english version).": "Please note that comments are shared across all realms but are locale specific (comments made on the french AHSpy site will not show up on the english version).",
	"Show price per item": "Show price per item",
	"Hide auctions with no buyout price": "Hide auctions with no buyout price",
	"Auctions table options": "Auctions table options",
	"World of Warcraft&reg; and Blizzard Entertainment are all trademarks or registered trademarks of Blizzard Entertainment in the United States and/or other countries.": "World of Warcraft&reg; and Blizzard Entertainment are all trademarks or registered trademarks of Blizzard Entertainment in the United States and/or other countries.",
	"This site is in no way associated with or endorsed by Blizzard Entertainment&reg;.": "This site is in no way associated with or endorsed by Blizzard Entertainment&reg;.",
	"Please choose a realm": "Please choose a realm",
	"EU Realms": "EU Realms",
	"US Realms": "US Realms",
	"Realm": "Realm",
	"Parlez-vous AHSpy?": "Parlez-vous AHSpy?",
	"What is AHSpy?": "What is AHSpy?",
	"AHSpy is an awesome new tool that let's you see World of Warcraft auctions and item pricing information in real time. Not only is AHSpy incredibly easy to use, it will also allow you to see the value of any actionable item in the last 30 days in any realm/faction. You will also be able to see the auction history of any seller. And because we get our data directly from Battle.Net and not from user uploads, we know that our stats are as exact as they can be.": "AHSpy is an awesome new tool that let's you see World of Warcraft auctions and item pricing information in real time. Not only is AHSpy incredibly easy to use, it will also allow you to see the value of any actionable item in the last 30 days in any realm/faction. You will also be able to see the auction history of any seller. And because we get our data directly from Battle.Net and not from user uploads, we know that our stats are as exact as they can be.",
	"Search results for \"%s\"": "Search results for \"%s\"",
	"%s item found": {
		"one": "%s item found",
		"other": "%s items found"
	},
	"Item name": "Item name"
}