{
	".contributors": "",
	".web": {
		"Average bid": "Average bid",
		"Average buyout": "Average buyout",
		"Quantity": "Quantity",
		"Average price per item for %s on %s (%s) - %s": "Average price per item for %s on %s (%s) - %s",
		"Alliance": "Alliance",
		"Horde": "Horde",
		"Neutral": "Neutral",
		"Date and time are based on the UTC/GMT timezone": "Date and time are based on the UTC/GMT timezone",
		"Ended": "Ended",
		"Short": "Short",
		"Medium": "Medium",
		"Long": "Long",
		"Very long": "Very long",
		"Less than 30 minutes": "Less than 30 minutes",
		"Between 30 minutes and 2 hours": "Between 30 minutes and 2 hours",
		"Between 2 hours and 12 hours": "Between 2 hours and 12 hours",
		"More than 12 hours": "More than 12 hours",
		"No realm matched your filter, please click another letter.": "No realm matched your filter, please click another letter.",
		"Price": "Price",
		"Bid": "Bid",
		"Buyout": "Buyout",
		"Quantity posted for sale on that day": "Quantity posted for sale on that day",
		"Auctions created on that day": "Auctions created on that day",
		"Not available": "Not available",
		"%d item found in %%s": {
			"one": "%d item found in %%s",
			"other": "%d items found in %%s"
		},
		"%d auction": {
			"one": "%d auction",
			"other": "%d auctions"
		},
		"%d hidden": {
			"one": "%d hidden",
			"other": "%d hidden"
		},
		"There is no active auction for this item": "There is no active auction for this item",
		"Last update: %s": "Last update: %s",
		"Total bid": "Total bid",
		"Total buyout": "Total buyout",
		"Per item": "Per item",
		"Apply": "Apply",
		"Cancel": "Cancel",
		"Gold": "Gold",
		"Silver": "Silver",
		"Copper": "Copper",
		"Harmonic Mean": "Harmonic Mean",
		"Harmonic mean comparaison for all %s realms": "Harmonic mean comparaison for all %s realms",
		"Average Price": "Average Price",
		"Quantity Posted": "Quantity Posted",
		"Last 7 days": "Last 7 days",
		"Last 31 days": "Last 31 days",
		"%d item": {
			"one": "%d item",
			"other": "%d items"
		},
  	"Time Left": "Time Left",
  	"First Seen": "First Seen",
  	"Auctions": "Auctions",
  	"%d auctions": {
			"one": "%d auction",
			"other": "%d auctions"
		},
    "Minimum Price": "Minimum Price",
    "Maximum Price": "Maximum Price"
	},
	".chart": {
		"decimalPoint": ".",
		"downloadPNG": "Download PNG image",
		"downloadJPEG": "Download JPEG image",
		"downloadPDF": "Download PDF document",
		"downloadSVG": "Download SVG vector image",
		"exportButtonTitle": "Export to raster or vector image",
		"loading": "Loading data",
		"printButtonTitle": "Print the chart",
		"rangeSelectorFrom": "From",
		"rangeSelectorTo": "To",
		"rangeSelectorZoom": "Zoom",
		"resetZoom": "Reset zoom",
		"resetZoomTitle": "Reset zoom level 1:1",
		"thousandsSep": ","
	},
	"Alliance": "Alliance",
	"Click here to change the active realm": "Click here to change the active realm",
	"Price per item - Last 48 hours": "Price per item - Last 48 hours",
	"Bid": "Bid",
	"Buyout": "Buyout",
	"Horde": "Horde",
	"Neutral": "Neutral",
	"Options": "Options",
	"Watch": "Watch",
	"Qty": "Qty",
	"Bids": "Bids",
	"Seller": "Seller",
	"Time Left": "Time Left",
	"Check %s at Wowhead": "Check %s at Wowhead",
	"Please note that comments are shared across all realms but are locale specific (comments made on the french AHSpy site will not show up on the english version).": "Please note that comments are shared across all realms but are locale specific (comments made on the french AHSpy site will not show up on the english version).",
	"Show price per item": "Show price per item",
	"Hide auctions with no buyout price": "Hide auctions with no buyout price",
	"Auctions table options": "Auctions table options",
	"World of Warcraft&reg; and Blizzard Entertainment are all trademarks or registered trademarks of Blizzard Entertainment in the United States and/or other countries.": "World of Warcraft&reg; and Blizzard Entertainment are all trademarks or registered trademarks of Blizzard Entertainment in the United States and/or other countries.",
	"This site is in no way associated with or endorsed by Blizzard Entertainment&reg;.": "This site is in no way associated with or endorsed by Blizzard Entertainment&reg;.",
	"Please choose a realm": "Please choose a realm",
	"EU Realms": "EU Realms",
	"US Realms": "US Realms",
	"Realm": "Realm",
	"Parlez-vous AHSpy?": "Parlez-vous AHSpy?",
	"What is AHSpy?": "What is AHSpy?",
	"AHSpy is an awesome new tool that lets you see World of Warcraft auctions and item pricing information in real time. Not only is AHSpy incredibly easy to use, it will also allow you to see the value of any auctionable item in the last 30 days in any realm/faction. You will also be able to see the auction history of any seller. And because we get our data directly from Battle.Net and not from user uploads, we know that our stats are as exact as they can be.": "AHSpy is an awesome new tool that lets you see World of Warcraft auctions and item pricing information in real time. Not only is AHSpy incredibly easy to use, it will also allow you to see the value of any auctionable item in the last 30 days in any realm/faction. You will also be able to see the auction history of any seller. And because we get our data directly from Battle.Net and not from user uploads, we know that our stats are as exact as they can be.",
	"Search results for \"%s\"": "Search results for \"%s\"",
	"%s item found": {
		"one": "%s item found",
		"other": "%s items found"
	},
	"Item Name": "Item Name",
	"We're currently importing the auctions data from our old database into the new one. The charts for some items might be empty or incomplete.": "We're currently importing the auctions data from our old database into the new one. The charts for some items might be empty or incomplete.",
	"Use AHSpy in your language! Simply use the appropriate subdomain and you should be all set!": "Use AHSpy in your language! Simply use the appropriate subdomain and you should be all set!",
	"These links will be integrated in a better navigation menu soon. If you wish to help us translate AHSpy, please take a look at our [GitHub project](https://github.com/Fuitad/AHSpy-i18n).": "These links will be integrated in a better navigation menu soon. If you wish to help us translate AHSpy, please take a look at our [GitHub project](https://github.com/Fuitad/AHSpy-i18n).",
	"AHSpy launched publicly on June 20th 2011 and is currently in early beta so please keep this in mind while you browse around the site. To stay informed on all the changes we make, keep an eye on our [Patch notes](http://docs.ahspy.com/patch-notes/) and [Roadmap](http://docs.ahspy.com/roadmap/) pages. If you want to make a suggestion or report a bug, please use our [feedback form](http://docs.ahspy.com/feedback/).": "AHSpy launched publicly on June 20th 2011 and is currently in early beta so please keep this in mind while you browse around the site. To stay informed on all the changes we make, keep an eye on our [Patch notes](http://docs.ahspy.com/patch-notes/) and [Roadmap](http://docs.ahspy.com/roadmap/) pages. If you want to make a suggestion or report a bug, please use our [feedback form](http://docs.ahspy.com/feedback/).",
	"And of course, the AHSpy [Facebook page](https://www.facebook.com/pages/AHSpy/174665455926869) and [Twitter feed](http://twitter.com/#!/ahspy) are two great ways to be notified as soon as we add new features.": "And of course, the AHSpy [Facebook page](https://www.facebook.com/pages/AHSpy/174665455926869) and [Twitter feed](http://twitter.com/#!/ahspy) are two great ways to be notified as soon as we add new features.",
	"Comments powered by": "Comments powered by",
	"No item found using your search criteria.": "No item found using your search criteria.",
	"The item either doesn't exist, it can't be sold on the auction house or we just haven't seen it at least once yet.": "The item either doesn't exist, it can't be sold on the auction house or we just haven't seen it at least once yet.",
	"Item #%s does not exist in our database or is invalid.": "Item #%s does not exist in our database or is invalid.",
	"Realm %s (%s) does not exist in our database or is invalid.": "Realm %s (%s) does not exist in our database or is invalid.",
	"If you believe that this is an error, please let us know!": "If you believe that this is an error, please let us know!",
	"Average bid per item - Last month": "Average bid per item - Last month",
	"Average buyout per item - Last month": "Average buyout per item - Last month",
	"Loading data": "Loading data",
	"Sign In to AHSpy": "Sign In to AHSpy",
	"Sign Out": "Sign Out",
	"Stay Connected": "Stay Connected",
	"Read the AHSpy blog": "Read the AHSpy blog",
	"Follow us on Twitter at @AHSpy": "Follow us on Twitter at @AHSpy",
	"\"Like\" AHSpy on Facebook": "\"Like\" AHSpy on Facebook",
	"Feedback": "Feedback",
	"Profile": "Profile",
	"Watch List": "Watch List",
	"Sign In": "Sign In",
	"Do you already have an account on one of these sites? If so, it means you also have an AHSpy account!": "Do you already have an account on one of these sites? If so, it means you also have an AHSpy account!",
	"Click the logo to log in with it here:": "Click the logo to log in with it here:",
	"locale_en_fullName": "English",
	"locale_fr_fullName": "Français",
	"locale_de_fullName": "Deutsch",
	"locale_es_fullName": "Español",
	"locale_ru_fullName": "Русский",
	"Active": "Active",
	"Last 7 days": "Last 7 days",
	"Last 31 days": "Last 31 days",
	"Per item": "Per item",
	"Per stack": "Per stack",
	"Pct": "Pct",
	"Date and time are based on the UTC/GMT timezone": "Date and time are based on the UTC/GMT timezone",
	"Quantity posted per day and per hour": "Quantity posted per day and per hour",
	"Auctions Created": "Auctions Created",
	"Quantity Posted": "Quantity Posted",
	"Minimum Price": "Minimum Price",
	"Maximum Price": "Maximum Price",
	"Average Price": "Average Price",
	"Harmonic Mean": "Harmonic Mean",
	"Standard Deviation": "Standard Deviation",
	"Auctions": "Auctions",
	"Average price": "Average price",
	"Check out the pricing info for %s on %s (%s) #WoW": "Check out the pricing info for %s on %s (%s) #WoW",
	"Tweet about %s on %s (%s)": "Tweet about %s on %s (%s)",
	"Add this item to my watch list": "Add this item to my watch list",
	"Market Price": "Market Price",
	"Watch Item": "Watch Item",
	"Region": "Region",
	"Total": "Total",
	"Average Market Price": "Average Market Price",
	"Useful information about the World of Warcraft auction house and economy": "Useful information about the World of Warcraft auction house and economy"
}