{
	"Alliance": "Alliance",
	"Click here to change the active realm": "Cliquez ici pour changer le royaume actuel",
	"Price per item - Last 48 hours": "Prix par article - Dernières 48 heures",
	"Average price per item - Last month": "Prix moyen par objet - Dernier mois",
	"Bid": "Enchère",
	"Buyout": "Achat immédiat",
	"Horde": "Horde",
	"Neutral": "Neutre",
	"Options": "Options",
	"Watch": "Voir",
	"Qty": "Qte",
	"Bids": "Enchères",
	"Seller": "Vendeur",
	"Time Left": "Temps restant",
	"Check %s at Wowhead": "Voir %s sur Wowhead",
	"Please note that comments are shared across all realms but are locale specific (comments made on the french AHSpy site will not show up on the english version).": "Veuillez noter que les commentaires sont partagés entre tous les royaumes de votre région. (Les commentaires publiés sur la version française du site AHSpy ne seront pas présents sur la version anglaise).",
	"Show price per item": "Voir le prix par objet",
	"Hide auctions with no buyout price": "Cacher les enchères qui n'ont pas l'option d'Achat immédiat.",
	"Auctions table options": "Options du tableau des ventes",
	"World of Warcraft&reg; and Blizzard Entertainment are all trademarks or registered trademarks of Blizzard Entertainment in the United States and/or other countries.": "World of Warcraft&reg; et Blizzard Entertainment sont des marques commerciales ou des marques déposées de Blizzard Entertainment aux États-Unis et / ou dans d'autres pays.",
	"This site is in no way associated with or endorsed by Blizzard Entertainment&reg;.": "Ce site n'est pas associé de quelque manière que ce soit avec Blizzard Entertainment&reg;.",
	"Please choose a realm": "Merci de choisir un royaume",
	"EU Realms": "Royaumes EU",
	"US Realms": "Royaumes US",
	"Realm": "Royaume",
	"Parlez-vous AHSpy?": "Parlez-vous AHSpy ?",
	"What is AHSpy?": "Qu'est-ce que AHSpy ?",
	"AHSpy is an awesome new tool that lets you see World of Warcraft auctions and item pricing information in real time. Not only is AHSpy incredibly easy to use, it will also allow you to see the value of any auctionable item in the last 30 days in any realm/faction. You will also be able to see the auction history of any seller. And because we get our data directly from Battle.Net and not from user uploads, we know that our stats are as exact as they can be.": "AHSpy est un nouvel outil formidable vous permettant de voir en temps réel l’ensemble des objets à l’hôtel des ventes de World of Warcraft. Non seulement AHSpy est incroyablement facile à utiliser mais il vous permettra en plus de voir le prix de n’importe quel objet en vente sur 30 derniers jours quel que soit le royaume ou la faction. Vous serez également en mesure de consulter l’historique des enchères d’un vendeur. Et ceci parce que nous obtenons nos données directement depuis Battle.net et non depuis l’envoi des données des utilisateurs. Nous savons que nos statistiques sont aussi exactes car elles peuvent l’être.",
	"Search results for \"%s\"": "Résultats de recherche pour \"%s\"",
	"%s item found": {
		"one": "%s objet trouvé",
		"other": "%s objets trouvés"
	},
	"Item name": "Nom de l'objet",
	"We're currently importing the auctions data from our old database into the new one. The charts for some items might be empty or incomplete.": "Nous sommes actuellement en train d’importer les données des ventes aux enchères depuis notre ancienne base de données vers la nouvelle. Les graphiques de certains objets peuvent être vides ou incomplets.",
	"Use AHSpy in your language! Simply use the appropriate subdomain and you should be all set!": "Utilisez AHspy dans votre langue ! Utilisez simplement le sous-domaine approprié et tout devrait être prêt !",
	"These links will be integrated in a better navigation menu soon. If you wish to help us translate AHSpy, please take a look at our [GitHub project](https://github.com/Fuitad/AHSpy-i18n).": "Ces liens seront bientôt intégrés dans un menu de navigation amélioré. Si vous voulez nous aider à traduire AHSpy, rendez-vous sur notre [Projet Github](https://github.com/Fuitad/AHSpy-i18n).",
	"If you run a WoW related website or if you're a developer, you can use our free API to get access to all our data easily. For more information, check our [API documentation](http://docs.ahspy.com/api/).": "Si vous avez un site web lié à l’univers de WoW ou si vous êtes un développeur, vous pouvez utiliser nos API gratuitement et accéder à nos données facilement. Pour plus d’informations, consultez notre [documentation API](http://docs.ahspy.com/api/).",
	"AHSpy launched publicly on June 20th 2011 and is currently in early beta so please keep this in mind while you browse around the site. To stay informed on all the changes we make, keep an eye on our [Patch notes](http://docs.ahspy.com/patch-notes/) and [Roadmap](http://docs.ahspy.com/roadmap/) pages. If you want to make a suggestion or report a bug, please use our [feedback form](http://docs.ahspy.com/feedback/).": "AHSpy a été lancé publiquement le 20 juin 2011 et est actuellement en version beta, gardez cela à l’esprit quand vous naviguez sur le site. Pour rester informé de toutes les modifications que nous faisons, gardez un œil sur nos [Notes de mise à jour](http://docs.ahspy.com/patch-notes/) et sur notre [planning](http://docs.ahspy.com/roadmap/). Si vous souhaitez faire une suggestion ou signaler un bug, merci d’utiliser notre [formulaire de retour]( http://docs.ahspy.com/feedback/).",
	"And of course, the AHSpy [Facebook page](https://www.facebook.com/pages/AHSpy/174665455926869) and [Twitter feed](http://twitter.com/#!/ahspy) are two great ways to be notified as soon as we add new features.": "Suivez AHSpy aussi sur sa [Page Facebook](https://www.facebook.com/pages/AHSpy/174665455926869) et son compte [Twitter](http://twitter.com/#!/ahspy) qui sont deux excellents moyens d’être informé dès que nous ajoutons de nouvelles fonctionnalités.",
	"Comments powered by": "Commentaires propulsés par",
	"No item found using your search criteria.": "Aucun objet trouvé avec ce critère de recherche.",
	"The item either doesn't exist, it can't be sold on the auction house or we just haven't seen it at least once yet.": "L'objet recherché n'existe pas. Soit parce qu'il ne peux pas être vendu à l'hôtel des ventes soit parce qu'il n'a pas encore été vu au moins une fois."
}