{
	"Alliance": "Alliance",
	"Click here to change the active realm": "Cliquez ici pour changer le royaume actuel",
	"Price per item - Last 48 hours": "Prix par article - Dernières 48 heures",
	"Average price per item - Last month": "Prix moyen par objet - Dernier mois",
	"Bid": "Enchère",
	"Buyout": "Achat immédiat",
	"Horde": "Horde",
	"Neutral": "Neutre",
	"Options": "Options",
	"Watch": "Voir",
	"Qty": "Qte",
	"Bids": "Enchères",
	"Seller": "Vendeur",
	"Time Left": "Temps restant",
	"Check %s at Wowhead": "Voir %s sur Wowhead",
	"Please note that comments are shared across all realms but are locale specific (comments made on the french AHSpy site will not show up on the english version).": "Veuillez noter que les commentaires sont partagès entre tous les royaumes de votre règion. (Les commentaires publiès sur la version française du site AHSpy ne seront pas prèsents sur la version anglaise).",
	"Show price per item": "Voir le prix par objet",
	"Hide auctions with no buyout price": "Cacher les enchères qui n'ont pas l'option d'Achat immèdiat.",
	"Auctions table options": "Options du tableau des ventes",
	"World of Warcraft&reg; and Blizzard Entertainment are all trademarks or registered trademarks of Blizzard Entertainment in the United States and/or other countries.": "World of Warcraft&reg; et Blizzard Entertainment sont des marques commerciales ou des marques dèposèes de Blizzard Entertainment aux États-Unis et / ou dans d'autres pays.",
	"This site is in no way associated with or endorsed by Blizzard Entertainment&reg;.": "Ce site n'est pas associè de quelque manière que ce soit avec Blizzard Entertainment&reg;.",
	"Please choose a realm": "Merci de choisir un royaume",
	"EU Realms": "Royaumes EU",
	"US Realms": "Royaumes US",
	"Realm": "Realm",
	"Parlez-vous AHSpy?": "Parlez-vous AHSpy ?",
	"What is AHSpy?": "Qu'est-ce que AHSpy ?",
	"AHSpy is an awesome new tool that let's you see World of Warcraft auctions and item pricing information in real time. Not only is AHSpy incredibly easy to use, it will also allow you to see the value of any actionable item in the last 30 days in any realm/faction. You will also be able to see the auction history of any seller. And because we get our data directly from Battle.Net and not from user uploads, we know that our stats are as exact as they can be.": "AHSpy est un nouvel outil formidable vous permettant de voir en temps rèel l’ensemble des objets &agrave; l’h&ocirc;tel des ventes de World of Warcraft. Non seulement AHSpy est incroyablement facile &agrave; utiliser mais il vous permettra en plus de voir le prix de n’importe quel objet en vente sur 30 derniers jours quel que soit le royaume ou la faction. Vous serez ègalement en mesure de consulter l’historique des enchères d’un vendeur. Et ceci parce que nous obtenons nos donnèes directement depuis Battle.net et non depuis l’envoi des donnèes des utilisateurs. Nous savons que nos statistiques sont aussi exactes car elles peuvent l’&ecirc;tre.",
	"Search results for \"%s\"": "Rèsultats de recherche pour \"%s\"",
	"%s item found": {
		"one": "%s objet trouvé",
		"other": "%s objets trouvés"
	},
	"Item name": "Nom de l'objet",
	"We're currently importing the auctions data from our old database into the new one. The charts for some items might be empty or incomplete.": "We're currently importing the auctions data from our old database into the new one. The charts for some items might be empty or incomplete."
}