{
	".contributors": "",
	".web": {
		"Average bid": "Média: Lances",
		"Average buyout": "Média: Arremate",
		"Quantity": "Quantidade",
		"Average price per item for %s on %s (%s) - %s": "Média de preço por item para %s em %s (%s) - %s",
		"Alliance": "Aliança",
		"Horde": "Horda",
		"Neutral": "Neutro",
		"Date and time are based on the UTC/GMT timezone": "Datas e horas baseadas no fuso UTC/GMT",
		"Ended": "Finalizado",
		"Short": "Curto",
		"Medium": "Médio",
		"Long": "Longo",
		"Very long": "Muito longo",
		"Less than 30 minutes": "Menos de 30 minutos",
		"Between 30 minutes and 2 hours": "Entre 30 minutos e 2 horas",
		"Between 2 hours and 12 hours": "Entre 2 horas e 12 horas",
		"More than 12 hours": "Mais de 12 horas",
		"No realm matched your filter, please click another letter.": "Nenhum reino encontrado com o filtro, por favor selecione outra letra.",
		"Price": "Preço",
		"Bid": "Lance",
		"Buyout": "Arremate",
		"Quantity posted for sale on that day": "Quantidade colocada a venda naquele dia",
		"Auctions created on that day": "Leilões criados naquele dia",
		"Not available": "Não disponível",
		"%d item found in %%s": {
			"one": "%d item encontrado em %%s",
			"other": "%d itens encontrados em %%s"
		},
		"%d hidden": {
			"one": "%d não visível",
			"other": "%d não visíveis"
		},
		"There is no active auction for this item": "Não existe leilão ativo para este item",
		"Last update: %s": "Última atualização: %s",
		"Total bid": "Total: Lances",
		"Total buyout": "Total: Arremates",
		"Per item": "Por item",
		"Apply": "Aplicar",
		"Cancel": "Cancelar",
		"Gold": "Ouro",
		"Silver": "Prata",
		"Copper": "Cobre",
		"Harmonic Mean": "Média Harmônica",
		"Harmonic mean comparaison for all %s realms": "Comparação da Média Harmônica para todos os reinos %s",
		"Average Price": "Preço Médio",
		"Quantity Posted": "Quantidade Colocada",
		"Last 7 days": "Últimos 7 dias",
		"Last 31 days": "Últimos 31 dias",
		"%d auction": {
			"one": "%d leilão",
			"other": "%d leilões"
		},
		"<span class=\"numfor\">%d</span> item": {
			"one": "<span class=\"numfor\">%d</span> item",
			"other": "<span class=\"numfor\">%d</span> itens"
		},
		"Time Left": "Tempo Restante",
		"First Seen": "Visto em",
		"Auctions": "Leilões",
		"Minimum Price": "Preço Mínimo",
		"Maximum Price": "Preço Máximo",
		"decimal_separator": ",",
		"thousands_separator": "."
	},
	".chart": {
		"decimalPoint": ",",
		"downloadPNG": "Download imagem PNG",
		"downloadJPEG": "Download imagem JPEG",
		"downloadPDF": "Download documento PDF",
		"downloadSVG": "Download imagem em vetor SVG",
		"exportButtonTitle": "Exportar para raterização ou imagem vetor",
		"loading": "Carregando dados",
		"printButtonTitle": "Imprimir ficha",
		"rangeSelectorFrom": "De",
		"rangeSelectorTo": "Para",
		"rangeSelectorZoom": "Zoom",
		"resetZoom": "Resetar zoom",
		"resetZoomTitle": "Resetar zoom level 1:1",
		"thousandsSep": "."
	},
	"Alliance": "Aliança",
	"Click here to change the active realm": "Clique aqui para mudar o reino ativo",
	"Price per item - Last 48 hours": "Preço por item - Últimas 48 horas",
	"Bid": "Lance",
	"Buyout": "Arremate",
	"Horde": "Horda",
	"Neutral": "Neutro",
	"Options": "Opções",
	"Watch": "Observar",
	"Qty": "Qtd",
	"Bids": "Lances",
	"Seller": "Vendedor",
	"Time Left": "Tempo Restante",
	"Check %s at Wowhead": "Checar %s no Wowhead",
	"Please note that comments are shared across all realms but are locale specific (comments made on the french AHSpy site will not show up on the english version).": "Por favor note que os comentários são distribuídos por todos os reinos, mas são restritos por localização (comentários feitos na versão em português do AHSpy não iram aparecer na versão em inglês).",
	"Show price per item": "Mostrar preço por item",
	"Hide auctions with no buyout price": "Esconder leilões sem preço de arremate",
	"Auctions table options": "Opções da tabela de leilões",
	"World of Warcraft&reg; and Blizzard Entertainment are all trademarks or registered trademarks of Blizzard Entertainment in the United States and/or other countries.": "World of Warcraft&reg; e Blizzard Entertainment são marcas ou  marcas registradas pela Blizzard Entertainment nos Estados Unidos e/ou em outros países.",
	"This site is in no way associated with or endorsed by Blizzard Entertainment&reg;.": "Este site não é associados com ou endossado pela Blizzard Entertainment&reg;.",
	"Please choose a realm": "Por favor escolha um reino",
	"EU Realms": "Reinos EU",
	"US Realms": "Reinos US",
	"Realm": "Reino",
	"Parlez-vous AHSpy?": "Parlez-vous AHSpy?",
	"What is AHSpy?": "O que é AHSpy?",
	"AHSpy is an awesome new tool that lets you see World of Warcraft auctions and item pricing information in real time. Not only is AHSpy incredibly easy to use, it will also allow you to see the value of any auctionable item in the last 30 days in any realm/faction. You will also be able to see the auction history of any seller. And because we get our data directly from Battle.Net and not from user uploads, we know that our stats are as exact as they can be.": "AHSpy é uma incrível nova ferramenta que deixa você ver leilões do World of Warcraft e informações de preços dos itens em tempo real. Não somente AHSpy é fácil de usar, como também deixará você ver o valor de qualquer item leiloado nos últimos 30 dias em qualquer reino/facção. Você também poderá ver o histórico de leilões de qualquer vendedor. Como nós obtemos os dados diretamente da Battle.Net e não de dados enviados por usuários, nós sabemos que nossas estatísticas são tão exatas quanto possível.",
	"Search results for \"%s\"": "Resultados da busca por \"%s\"",
	"%s item found": {
		"one": "%s item encontrado",
		"other": "%s itens encontrados"
	},
	"Item Name": "Nome do Item",
	"We're currently importing the auctions data from our old database into the new one. The charts for some items might be empty or incomplete.": "No momento estamos importando os dados dos leilões da nossa antiga base de dados para a nova. Os gráficos de alguns itens podem estar vazios ou inclompletos.",
	"Use AHSpy in your language! Simply use the appropriate subdomain and you should be all set!": "Use AHSpy na sua lingua! Simplesmente use o sub-domínio apropriado e tudo deve estar ok!",
	"These links will be integrated in a better navigation menu soon. If you wish to help us translate AHSpy, please take a look at our [GitHub project](https://github.com/Fuitad/AHSpy-i18n).": "Estes links serão integrados em um novo menu de navegação em breve. Se quiser nos ajudar a traduzir AHSpy, por favor visite nosso projeto no [GitHub](https://github.com/Fuitad/AHSpy-i18n).",
	"AHSpy launched publicly on June 20th 2011 and is currently in early beta so please keep this in mind while you browse around the site. To stay informed on all the changes we make, keep an eye on our [Patch notes](http://docs.ahspy.com/patch-notes/) and [Roadmap](http://docs.ahspy.com/roadmap/) pages. If you want to make a suggestion or report a bug, please use our [feedback form](http://docs.ahspy.com/feedback/).": "AHSpy foi lançado ao publico em 20 de Junho de 2011 e está em fase beta lembre-se disso ao navegar pelo site. Para se manter informado de todas as mudanças que fizermos, visite sempre nossas [Notas de Atualização](http://docs.ahspy.com/patch-notes/) e nosso [Roadmap](http://docs.ahspy.com/roadmap/). Se quiser fazer uma suggestão ou reportar um problema, por favor use nosso [Formulário de Feedback](http://docs.ahspy.com/feedback/).",
	"And of course, the AHSpy [Facebook page](https://www.facebook.com/pages/AHSpy/174665455926869) and [Twitter feed](http://twitter.com/#!/ahspy) are two great ways to be notified as soon as we add new features.": "E claro, a página da AHSpy no [Facebook](https://www.facebook.com/pages/AHSpy/174665455926869) e [Twitter](http://twitter.com/#!/ahspy) são duas exelentes maneiras de ser notificado assim que adicionarmos novas funcionalidades.",
	"Comments powered by": "Comentários alimentados por",
	"No item found using your search criteria.": "Nenhum item encontrado usando seus critérios de busca.",
	"The item either doesn't exist, it can't be sold on the auction house or we just haven't seen it at least once yet.": "Este item não existe ou não pode ser vendido na Casa de Leilões ou nós não o vimos ainda.",
	"Item %d does not exist in our database or is invalid.": "O item %d não existe na nossa base de dados ou é inválido.",
	"Realm %s (%s) does not exist in our database or is invalid.": "O reino %s (%s) não existe na nossa base de dados ou é inválido.",
	"If you believe that this is an error, please let us know!": "Se você acredita que isso é um erro, por favor nos avise!",
	"Average bid per item - Last month": "Média de lances por item - Último mês",
	"Average buyout per item - Last month": "Média de arremates por item - Último mês",
	"Loading data": "Carregando dados",
	"Sign In to AHSpy": "Entrar no AHSpy",
	"Sign Out": "Sair",
	"Stay Connected": "Mantenha-se Conectado",
	"Read the AHSpy blog": "Leia o blog do AHSpy",
	"Follow us on Twitter at @AHSpy": "Nos siga no Twitter em @AHSpy",
	"\"Like\" AHSpy on Facebook": "\"Curtir\" AHSpy no Facebook",
	"Feedback": "Feedback",
	"Profile": "Perfil",
	"Watch List": "Produtos em Vista",
	"Sign In": "Entrar",
	"Do you already have an account on one of these sites? If so, it means you also have an AHSpy account!": "Se você já tem uma conta em algum destes sites, significa que você também já tem uma conta no AHSpy!",
	"Click the logo to log in with it here:": "Clique no logo para entrar:",
	"locale_en_fullName": "Inglês",
	"locale_fr_fullName": "Françes",
	"locale_de_fullName": "Alemão",
	"locale_es_fullName": "Espanhol",
	"locale_ru_fullName": "Russo",
	"Active": "Ativo",
	"Last 7 days": "Últimos 7 dias",
	"Last 31 days": "Últimos 31 dias",
	"Per item": "Por item",
	"Per stack": "Por lote",
	"Pct": "%",
	"Date and time are based on the UTC/GMT timezone": "Datas e horas baseadas no fuso UTC/GMT",
	"Quantity posted per day and per hour": "Quantidade colocada por dia e por hora",
	"Auctions Created": "Leilões Criados",
	"Quantity Posted": "Quantidade Colocada",
	"Minimum Price": "Preço Mínimo",
	"Maximum Price": "Preço Máximo",
	"Average Price": "Preço Médio",
	"Harmonic Mean": "Média Harmônica",
	"Standard Deviation": "Desvio Padrão",
	"Auctions": "Leilões",
	"%d auctions": {
		"one": "%d leilão",
		"other": "%d leilões"
	},
	"%d item": {
		"one": "%d item",
		"other": "%d itens"
	},
	"Average price": "Preço Médio",
	"Check out the pricing info for %s on %s (%s) #WoW": "Olha só o preço de %s em %s (%s) #WoW",
	"Tweet about %s on %s (%s)": "Tuíte sobre %s em %s (%s)",
	"Add this item to my watch list": "Adicione este item nos meus Produtos em Vista",
	"Market Price": "Preço de Mercado",
	"Watch Item": "Observar item",
	"Region": "Região",
	"Total": "Total",
	"Average Market Price": "Média: Preço de Mercado",
	"Useful information about the World of Warcraft auction house and economy": "Informações úteis sobre a Casa de Leilões e a economia de World of Warcraft",
	"Summary": "Sumário",
	"View global page": "Ver página global",
	"Item name": "Nome do Item"
}