{
	".contributors": "hotZED",
	".web": {
		"Average bid": "Средняя ставка",
		"Average buyout": "Средний выкуп",
		"Quantity": "Количество",
		"Auctions": "Аукционы",
		"Average price per item for %s on %s (%s) - %s": "Средняя цена за предмет %s из %s (%s) - %s",
		"Alliance": "Альянс",
		"Horde": "Орда",
		"Neutral": "Нейтральный",
		"Date and time are based on the UTC/GMT timezone": "Дата и время, основаные на UTC/GMT часовом поясе",
		"Ended": "Окончен",
		"Short": "Короткий",
		"Medium": "Средний",
		"Long": "Долгий",
		"Very long": "Очень долгий",
		"Less than 30 minutes": "Менее 30 минут",
		"Between 30 minutes and 2 hours": "От 30 минт до 2 часов",
		"Between 2 hours and 12 hours": "От 2 до 12 часов",
		"More than 12 hours": "Более 12 часов",
		"No realm matched your filter, please click another letter.": "Не найдены игровые миры по вашему фильтру, полжалуйста, выберите другую букву.",
		"Price": "Цена",
		"Bid": "Ставка",
		"Buyout": "Выкуп",
		"Quantity posted for sale on that day": "Количество выставленное на продажу в этот день",
		"Auctions created on that day": "Создано аукционов в этот день",
		"Not available": "Не доступно",
    "%d item found in %%s": {
      "one": "%d предмет найден в %%s",
      "other": "%d предметов найдено в %%s"
    },
    "%d auction": {
      "one": "%d аукцион",
      "other": "%d аукционы"
    },
    "%d hidden": {
      "one": "%d скрыт",
      "other": "%d скрыты"
    },
    "There is no active auction for this item": "Нет активных аукционов для данной позиции",
    "Last update: %s": "Последнее обновление: %s",
		"Total bid": "Общая ставка",
		"Total buyout": "Общий выкуп",
		"Per item": "За предмет",
		"Apply": "Применить",
		"Cancel": "Отменить",
		"Gold": "Золото",
		"Silver": "Серебро",
		"Copper": "Медь",
		"Average price": "Average price",
		"Harmonic mean": "Harmonic mean",
		"Harmonic mean comparaison for all %s realms": "Harmonic mean comparaison for all %s realms",
    "Last 31 days": "Last 31 days",
    "Average Price": "Average Price",
    "Quantity Posted": "Quantity Posted"
	},
	".chart": {
	  "decimalPoint": ".",
    "downloadPNG": "Сохранить картинку в формате PNG",
    "downloadJPEG": "Сохранить картинку в формате JPEG",
    "downloadPDF": "Сохранить как документ PDF",
    "downloadSVG": "Сохранитт в формате SVG",
    "exportButtonTitle": "Экспортировать как растровое или векторное изображение",
    "loading": "Загрузка данных",
    "printButtonTitle": "Распечатать диаграмму",
    "rangeSelectorFrom": "От",
    "rangeSelectorTo": "До",
    "rangeSelectorZoom": "Увеличение",
    "resetZoom": "Сбросить масштаб",
    "resetZoomTitle": "Восстановить масштаб 1:1",
    "thousandsSep": ","
	},
	"Alliance": "Альянс",
	"Click here to change the active realm": "Кликните здесь, чтобы сменить выбранный игровой мир",
	"Price per item - Last 48 hours": "Цена за предмет - за последние 48 часов",
	"Bid": "Ставка",
	"Buyout": "Выкуп",
	"Horde": "Орда",
	"Neutral": "Нейтральный",
	"Options": "Опции",
	"Watch": "Следить",
	"Qty": "Кол-во",
	"Bids": "Ставки",
	"Seller": "Продавец",
	"Time Left": "Осталось времени",
	"Check %s at Wowhead": "Найти %s на Wowhead",
	"Please note that comments are shared across all realms but are locale specific (comments made on the french AHSpy site will not show up on the english version).": "Пожалуйста, обратите внимание, что комментарии являются общими для всех игровых миров, но имеется привязка к языку комментария (замечания, сделанные по французском сайте AHSpy не будет отображаться на английской версии).",
	"Show price per item": "Показать цену за предмет",
	"Hide auctions with no buyout price": "Скрыть аукционы без цены выкупа",
	"Auctions table options": "Параметры таблицы аукциона",
	"World of Warcraft&reg; and Blizzard Entertainment are all trademarks or registered trademarks of Blizzard Entertainment in the United States and/or other countries.": "World of Warcraft&reg; и Blizzard Entertainment являются зарегистрированными торговыми марками компании Blizzard Entertainment в США и/или других странах.",
	"This site is in no way associated with or endorsed by Blizzard Entertainment&reg;.": "Этот сайт никоим образом не связан или одобрен компанией Blizzard Entertainment&reg;.",
	"Please choose a realm": "Выберите игровой мир",
	"EU Realms": "EU игровые миры",
	"US Realms": "US игровые миры",
	"Realm": "Игровой мир",
	"Parlez-vous AHSpy?": "Parlez-vous AHSpy?",
	"What is AHSpy?": "Что такое AHSpy?",
	"AHSpy is an awesome new tool that lets you see World of Warcraft auctions and item pricing information in real time. Not only is AHSpy incredibly easy to use, it will also allow you to see the value of any auctionable item in the last 30 days in any realm/faction. You will also be able to see the auction history of any seller. And because we get our data directly from Battle.Net and not from user uploads, we know that our stats are as exact as they can be.": "AHSpy это удивительный новый инструмент, который позволяет вам видеть аукционы World of Warcraft и информацию о ценах на предметы в реальном времени. Мало того, что AHSpy невероятно прост в использовании, он также позволит Вам увидеть историю продажи предмета в течение последних 30 дней в любом игровом мире/фракции. Вы также сможете увидеть историю любого продавца на акционе. И потому, что мы получаем данные непосредственно из Battle.Net, а не просим загружать данные пользователя, мы знаем, что наша статистика настолько точна, насколько это возможно.",
	"Search results for \"%s\"": "Искать результаты для \"%s\"",
	"%s item found": {
		"one": "%s предмет найден",
		"other": "%s предметов найдено"
	},
	"Item name": "Название предмета",
	"We're currently importing the auctions data from our old database into the new one. The charts for some items might be empty or incomplete.": "В настоящее время мы импортируем данные аукционов из нашей старой базы данных в новую. Диаграммы по некоторым позициям могут быть пустыми или неполными.",
	"Use AHSpy in your language! Simply use the appropriate subdomain and you should be all set!": "Используйте AHSpy на Вашем языке! Просто выберите соответствующий поддомен и все готово!",
	"These links will be integrated in a better navigation menu soon. If you wish to help us translate AHSpy, please take a look at our [GitHub project](https://github.com/Fuitad/AHSpy-i18n).": "Эти ссылки будут интегрированы в меню навигации более выгодном виде в ближайшее время. Если вы хотите помочь нам перевести AHSpy, пожалуйста, посмотрите на наш [GitHub проект](https://github.com/Fuitad/AHSpy-i18n).",
	"If you run a WoW related website or if you're a developer, you can use our free API to get access to all our data easily. For more information, check our [API documentation](http://docs.ahspy.com/api/).": "Если у Вас есть свой веб-сайт WoW или Вы разработчик, Вы можете использовать наш бесплатный API, чтобы получить доступ ко всем нашим данным. Для получения дополнительной информации посетите нашу [API документацию](http://docs.ahspy.com/api/).",
	"AHSpy launched publicly on June 20th 2011 and is currently in early beta so please keep this in mind while you browse around the site. To stay informed on all the changes we make, keep an eye on our [Patch notes](http://docs.ahspy.com/patch-notes/) and [Roadmap](http://docs.ahspy.com/roadmap/) pages. If you want to make a suggestion or report a bug, please use our [feedback form](http://docs.ahspy.com/feedback/).": "AHSpy публично был запущен 20 июня 2011 года и в настоящее время находится в режиме бета,  поэтому, пожалуйста, имейте это в виду при использовании данного сайта. Чтобы оставаться в курсе всех изменений, которые мы осуществляем, следите за нашими [патч-нотами](http://docs.ahspy.com/patch-notes/) и [планами](http://docs.ahspy.com/roadmap/). Если у Вас есть предложения или Вы желаете сообщить об ошибке, пожалуйста, используйте нашу [форму обратной связи](http://docs.ahspy.com/feedback/).",
	"And of course, the AHSpy [Facebook page](https://www.facebook.com/pages/AHSpy/174665455926869) and [Twitter feed](http://twitter.com/#!/ahspy) are two great ways to be notified as soon as we add new features.": "И, конечно же, у AHSpy есть [страничка на Facebook](https://www.facebook.com/pages/AHSpy/174665455926869) и [новости в Twitter](http://twitter.com/#!/ahspy) - два быстрых способа быть в курсе всех новых изменений.",
	"Comments powered by": "Комментарии основаны на",
	"No item found using your search criteria.": "Не найден ни один предмет по Вашим критериям.",
	"The item either doesn't exist, it can't be sold on the auction house or we just haven't seen it at least once yet.": "Предмета не существует, или не продается на аукционе или мы его еще ни разу не видели.",
	"Item #%s does not exist in our database or is invalid.": "Предмет #%s не существует в нашей базе данных или указан не правильно.",
	"Realm %s (%s) does not exist in our database or is invalid.": "Игровой мир %s (%s) не найден в нашей базе данных или указан не правильно.",
	"If you believe that this is an error, please let us know!": "Если Вы уверены, что это ошибка, сообщите нам!",
	"Average bid per item - Last month": "Среденяя ставка за предмет - Последний месяц",
	"Average buyout per item - Last month": "Средений выкуп за предмет - Последний месяц",
	"Loading data": "Загрузка данных",
	"Sign In to AHSpy": "Войти в AHSpy",
	"Sign Out": "Выйти",
	"Stay Connected": "Оставайся на связи",
	"Read the AHSpy blog": "Прочитать блог AHSpy",
	"Follow us on Twitter at @AHSpy": "Следите за нами на Twitter: @AHSpy",
	"\"Like\" AHSpy on Facebook": "\"Мне нравится\" AHSpy на Facebook",
	"Feedback": "Обратная связь",
	"Profile": "Профиль",
	"Watch List": "Список отслеживания",
	"Sign In": "Войти",
	"Do you already have an account on one of these sites? If so, it means you also have an AHSpy account!": "У Вас уже есть учетная запись на одном из этих сайтов? Значит Вы также можете войти на AHSpy!",
	"Click the logo to log in with it here:": "Кликните на логотип, чтобы войти:",
	"locale_en_fullName": "English",
	"locale_fr_fullName": "Français",
	"locale_de_fullName": "Deutsch",
	"locale_es_fullName": "Español",
	"locale_ru_fullName": "Русский",
	"Pct": "Pct",
	"Active": "Active",
	"Last 7 days": "Last 7 days",
	"Last 31 days": "Last 31 days",
	"Per item": "Per item",
	"Per stack": "Per stack"
}