{
	"Realm": "Realm",
	"Click here to change the active realm": "Click here to change the active realm",
	"Parlez-vous AHSpy?": "Parlez-vous AHSpy?",
	"What is AHSpy?": "What is AHSpy?",
	"AHSpy is an awesome new tool that lets you see World of Warcraft auctions and item pricing information in real time. Not only is AHSpy incredibly easy to use, it will also allow you to see the value of any auctionable item in the last 30 days in any realm/faction. You will also be able to see the auction history of any seller. And because we get our data directly from Battle.Net and not from user uploads, we know that our stats are as exact as they can be.": "AHSpy is an awesome new tool that lets you see World of Warcraft auctions and item pricing information in real time. Not only is AHSpy incredibly easy to use, it will also allow you to see the value of any auctionable item in the last 30 days in any realm/faction. You will also be able to see the auction history of any seller. And because we get our data directly from Battle.Net and not from user uploads, we know that our stats are as exact as they can be.",
	"World of Warcraft&reg; and Blizzard Entertainment are all trademarks or registered trademarks of Blizzard Entertainment in the United States and/or other countries.": "World of Warcraft&reg; and Blizzard Entertainment are all trademarks or registered trademarks of Blizzard Entertainment in the United States and/or other countries.",
	"This site is in no way associated with or endorsed by Blizzard Entertainment&reg;.": "This site is in no way associated with or endorsed by Blizzard Entertainment&reg;.",
	"Please choose a realm": "Please choose a realm",
	"EU Realms": "EU Realms",
	"US Realms": "US Realms",
	"Search results for \"%s\"": "Search results for \"%s\"",
	"%s item found": {
		"one": "%s item found",
		"other": "%s items found"
	},
	"Item name": "Item name",
	"We're currently importing the auctions data from our old database into the new one. The charts for some items might be empty or incomplete.": "We're currently importing the auctions data from our old database into the new one. The charts for some items might be empty or incomplete.",
	"Check %s at Wowhead": "Check %s at Wowhead",
	"Price per item - Last 48 hours": "Price per item - Last 48 hours",
	"Average price per item - Last month": "Average price per item - Last month",
	"Bid": "Bid",
	"Buyout": "Buyout",
	"Alliance": "Alliance",
	"Horde": "Horde",
	"Neutral": "Neutral",
	"Options": "Options",
	"Watch": "Watch",
	"Qty": "Qty",
	"Bids": "Bids",
	"Seller": "Seller",
	"Time Left": "Time Left",
	"Please note that comments are shared across all realms but are locale specific (comments made on the french AHSpy site will not show up on the english version).": "Please note that comments are shared across all realms but are locale specific (comments made on the french AHSpy site will not show up on the english version).",
	"Auctions table options": "Auctions table options",
	"Show price per item": "Show price per item",
	"Hide auctions with no buyout price": "Hide auctions with no buyout price",
	"Use AHSpy in your language! Simply use the appropriate subdomain and you should be all set!": "Use AHSpy in your language! Simply use the appropriate subdomain and you should be all set!",
	"These links will be integrated in a better navigation menu soon. If you wish to help us translate AHSpy, please take a look at our [GitHub project](https://github.com/Fuitad/AHSpy-i18n).": "These links will be integrated in a better navigation menu soon. If you wish to help us translate AHSpy, please take a look at our [GitHub project](https://github.com/Fuitad/AHSpy-i18n).",
	"If you run a WoW related website or if you're a developer, you can use our free API to get access to all our data easily. For more information, check our [API documentation](http://docs.ahspy.com/api/).": "If you run a WoW related website or if you're a developer, you can use our free API to get access to all our data easily. For more information, check our [API documentation](http://docs.ahspy.com/api/).",
	"AHSpy launched publicly on June 20th 2011 and is currently in early beta so please keep this in mind while you browse around the site. To stay informed on all the changes we make, keep an eye on our [Patch notes](http://docs.ahspy.com/patch-notes/) and [Roadmap](http://docs.ahspy.com/roadmap/) pages. If you want to make a suggestion or report a bug, please use our [feedback form](http://docs.ahspy.com/feedback/).": "AHSpy launched publicly on June 20th 2011 and is currently in early beta so please keep this in mind while you browse around the site. To stay informed on all the changes we make, keep an eye on our [Patch notes](http://docs.ahspy.com/patch-notes/) and [Roadmap](http://docs.ahspy.com/roadmap/) pages. If you want to make a suggestion or report a bug, please use our [feedback form](http://docs.ahspy.com/feedback/).",
	"And of course, the AHSpy [Facebook page](https://www.facebook.com/pages/AHSpy/174665455926869) and [Twitter feed](http://twitter.com/#!/ahspy) are two great ways to be notified as soon as we add new features.": "And of course, the AHSpy [Facebook page](https://www.facebook.com/pages/AHSpy/174665455926869) and [Twitter feed](http://twitter.com/#!/ahspy) are two great ways to be notified as soon as we add new features.",
	"Comments powered by": "Comments powered by"
}